name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::522814736381:role/GitHubActions
        aws-region: us-east-1

    - name: Sync files to S3
      run: aws s3 sync ./ResumeSite s3://andrewscloudres.com --delete
